#!/usr/bin/env node

const commander = require('commander');
const program = new commander.Command();
const prompts = require('prompts');

/**
 * Handler functions
 */
const handleSignUp = require('./src/commands/signup.js');

/**
 * Commands
 * -h (--help) is automatically generated by commander
 */
program.command('signup').action(handleSignUp);

program.parse(process.argv);
