#!/usr/bin/env node
const commander = require('commander');
const program = new commander.Command();

const welcomeScreen = require('./src/lib/welcome-screen.js');

/**
 * Handler functions
 */
const handleSignUp = require('./src/commands/handle_signup.js');
const handleSignIn = require('./src/commands/handle_signin.js');
const handlePlay = require('./src/commands/handle_play.js');
const handleLeaderboard = require('./src/commands/handle_leaderboard.js');
const handleSignOut = require('./src/commands/handle_signout.js');

/**
 * Commands
 * -h (--help) is automatically generated by commander
 */
program.command('signup').action(handleSignUp);
program.command('signin').action(handleSignIn);
program.command('play').action(handlePlay);
program.command('leaderboard').action(handleLeaderboard);
program.command('signout').action(handleSignOut);

/**
 * Show welcome screen when no command is provided
 */
if (!process.argv.slice(2).length) {
  welcomeScreen();
}

/**
 * Handle unsuported commands
 */
program.on('command:*', function() {
  console.error(
    'Invalid command: %s\nSee --help for a list of available commands.',
    program.args.join(' ')
  );
  program.outputHelp();
});

program.parse(process.argv);
