#!/usr/bin/env node
const commander = require('commander');
const program = new commander.Command();

const welcomeScreen = require('./lib/welcome_screen.js');

/**
 * Handler functions
 */
const handleSignUp = require('./commands/handle_signup.js');
const handleSignIn = require('./commands/handle_signin.js');
const handlePlay = require('./commands/handle_play.js');
const handleLeaderboard = require('./commands/handle_leaderboard.js');
const handleSignOut = require('./commands/handle_signout.js');

/**
 * Commands
 * -h (--help) is automatically generated by commander
 */

// Sign Up
program
  .command('signup')
  .description('Create a new account')
  .action(handleSignUp);

// Sign In
program
  .command('signin')
  .description('Sign in to an existing account')
  .action(handleSignIn);

// Play
program
  .command('play')
  .description('Play')
  .action(handlePlay);

// Leaderboard
program
  .command('leaderboard')
  .description('Show the leaderboard')
  .action(handleLeaderboard);

// Sign Out
program
  .command('signout')
  .description('Sign out')
  .action(handleSignOut);

/**
 * Show welcome screen when no command is provided
 */
if (!process.argv.slice(2).length) {
  welcomeScreen();
}

/**
 * Handle unsuported commands
 */
program.on('command:*', function() {
  console.error(
    'Invalid command: %s\nSee --help for a list of available commands.',
    program.args.join(' ')
  );
  program.outputHelp();
});

program.parse(process.argv);

exports.play;
